apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gvarph/homelab_kube.git
    targetRevision: HEAD
    path: apps/example-metrics
  destination:
    server: https://kubernetes.default.svc
    namespace: example-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true