apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-k8s
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/gvarph/homelab_kube.git
    targetRevision: HEAD
    path: apps/hello-k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-k8s
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

