apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
spec:
  project: default
  source:
    repoURL: https://github.com/gvarph/homelab_kube.git
    targetRevision: HEAD
    path: apps/victoria-logs
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-logs


