apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-configs
  namespace: victoria-metrics
type: Opaque
stringData:
  prometheus-additional.yaml: |
    # ArgoCD Application Controller metrics
    - job_name: 'argocd-metrics'
      static_configs:
      - targets: ['argocd-metrics.argocd.svc.cluster.local:8082']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    # ArgoCD API Server metrics
    - job_name: 'argocd-server-metrics'
      static_configs:
      - targets: ['argocd-server-metrics.argocd.svc.cluster.local:8083']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    # ArgoCD Repo Server metrics
    - job_name: 'argocd-repo-server-metrics'
      static_configs:
      - targets: ['argocd-repo-server.argocd.svc.cluster.local:8084']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    # ArgoCD Notifications Controller metrics
    - job_name: 'argocd-notifications-controller-metrics'
      static_configs:
      - targets: ['argocd-notifications-controller-metrics.argocd.svc.cluster.local:9001']
      metrics_path: '/metrics'
      scrape_interval: 30s
    
    # Kubernetes service discovery with Prometheus annotations
    - job_name: 'kubernetes-services-prometheus-annotations'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names: []  # Empty means all namespaces
      relabel_configs:
      # Exclude victoria-metrics namespace (handled by VMServiceScrape)
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: victoria-metrics
      
      # Only scrape services with prometheus.io/scrape=true annotation
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      
      # Use custom path if prometheus.io/path is set
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      
      # Use custom port if prometheus.io/port is set
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      
      # Use custom scheme if prometheus.io/scheme is set
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      
      # Add service name as job label
      - source_labels: [__meta_kubernetes_service_name]
        target_label: job
        replacement: ${1}
      
      # Add namespace label
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      
      # Add service labels as metrics labels
      - regex: __meta_kubernetes_service_label_(.+)
        action: labelmap
