apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-configs
  namespace: victoria-metrics
type: Opaque
stringData:
  prometheus-additional.yaml: |
    # Kubernetes service discovery with Prometheus annotations
    - job_name: 'kubernetes-services-prometheus-annotations'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names: []  # Empty means all namespaces
      relabel_configs:
      # Only scrape services with prometheus.io/scrape=true annotation
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      
      # Use custom path if prometheus.io/path is set
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      
      # Use custom port if prometheus.io/port is set
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      
      # Use custom scheme if prometheus.io/scheme is set
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      
      # Add service name as job label
      - source_labels: [__meta_kubernetes_service_name]
        target_label: job
        replacement: ${1}
      
      # Add namespace label
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      
      # Add service labels as metrics labels
      - regex: __meta_kubernetes_service_label_(.+)
        action: labelmap