victoria-metrics-k8s-stack:
  fullnameOverride: vm-k8s-stack
  defaultDashboards:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
  grafana:
    enabled: true
    plugins:
      - victoriametrics-logs-datasource
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaLogs
            type: victoriametrics-logs-datasource
            access: proxy
            url: http://victoria-logs.victoria-logs.svc.cluster.local:9428
            isDefault: false
