victoria-metrics-k8s-stack:
  fullnameOverride: vm-k8s-stack
  defaultDashboards:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
    labels:
      grafana_folder: victoria_metrics_default_dashboards
      grafana_dashboard: "1"
  grafana:
    enabled: true # We use a dedicated Grafana instance in it's own app
  
  # VictoriaMetrics single node configuration
  vmsingle:
    enabled: true
    spec:
      retentionPeriod: "30d"
      extraArgs:
        maxLabelsPerTimeseries: "60"  # Increase from default 40 to 60 (highest seen is 48)
        loggerFormat: "json"          # Enable structured JSON logging
      storage:
        storageClassName: "local-path"
        accessModes:
          - ReadWriteOnce
        size: 20Gi

  # Enable annotation-based service discovery
  vmagent:
    spec:
      # Add additional scrape configs for Prometheus annotation-based discovery
      additionalScrapeConfigs:
        name: prometheus-additional-configs
        key: prometheus-additional.yaml
      extraArgs:
        loggerFormat: "json"          # Enable structured JSON logging

  vmalert:
    spec:
      extraArgs:
        loggerFormat: "json"          # Enable structured JSON logging

  kube-state-metrics:
    metricLabelsAllowlist:
      - "pods=[app]"
    # Note: kube-state-metrics doesn't support JSON logging format
    # It uses standard Go logging which outputs to stderr by default

  prometheus-node-exporter:
    extraArgs:
      - --log.format=json          # Enable structured JSON logging

  vmalertmanager:
    spec:
      extraArgs:
        loggerFormat: "json"       # Enable structured JSON logging


