victoria-metrics-k8s-stack:
  fullnameOverride: vm-k8s-stack
  defaultDashboards:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
  grafana:
    enabled: true
    plugins:
      - victoriametrics-logs-datasource
