victoria-metrics-k8s-stack:
  fullnameOverride: vm-k8s-stack
  defaultDashboards:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
    labels:
      grafana_folder: victoria_metrics_default_dashboards
      grafana_dashboard: "1"
  grafana:
    enabled: false
