victoria-logs-single:
  vector:
    enabled: true
    env:
      - name: VECTOR_LOG_FORMAT
        value: json

  server:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9428"

    extraArgs:
      loggerFormat: json

  persistence:
    enabled: true
    size: 32Gi

  podDisruptionBudget:
    enabled: true

  dashboards:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
    labels:
      grafana_folder: victoria_logs_dashboards
      grafana_dashboard: "1"
