victoria-logs-single:
  vector:
    enabled: true

  server:
    enabled: true

  persistence:
    enabled: true
    size: 32Gi

  podDisruptionBudget:
    enabled: true

  dashboards:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
    labels:
      grafana_folder: victoria_logs_dashboards
      grafana_dashboard: "1"
