apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-metrics
  namespace: example-metrics
  labels:
    app: example-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-metrics
  template:
    metadata:
      labels:
        app: example-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"       
    spec:
      containers:
      - name: example-metrics
        image: prom/node-exporter
        ports:
        - containerPort: 9100
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      - name: cpu-burner
        image: ubuntu
        command:
          - /bin/bash
          - -c
          - |
            while true; do
              # Compute a hash repeatedly for 5 seconds to burn CPU
              end=$((SECONDS+5))
              while [ $SECONDS -lt $end ]; do
                echo "cpu load test" | sha256sum > /dev/null
              done
              echo "cpu load test done"
              sleep 10
            done
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: example-metrics
  labels:
    name: example-metrics
