apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-metrics
  namespace: example-metrics
  labels:
    app: example-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-metrics
  template:
    metadata:
      labels:
        app: example-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"       
    spec:
      containers:
      - name: example-metrics
        image: prom/node-exporter
        ports:
        - containerPort: 9100
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Namespace
metadata:
  name: example-metrics
  labels:
    name: example-metrics
