apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-metrics
  namespace: example-metrics
  labels:
    app: example-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-metrics
  template:
    metadata:
      labels:
        app: example-metrics
    spec:
      containers:
      - name: example-metrics
        image: prom/prometheus-example-app:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Namespace
metadata:
  name: example-metrics
  labels:
    name: example-metrics