{{- if .Values.eventExporter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "victoria-logs.eventExporter.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "victoria-logs.labels" . | nindent 4 }}
    app.kubernetes.io/component: event-exporter
data:
  config.yaml: |
    # Kubernetes Event Exporter Configuration
    # Exports Kubernetes events to Victoria Logs
    
    logLevel: info
    logFormat: json
    metricsNamePrefix: event_exporter_
    
    # Route all events to Victoria Logs
    route:
      routes:
        - match:
            - receiver: "victoria-logs"
    
    # Victoria Logs webhook receiver
    receivers:
      - name: "victoria-logs"
        webhook:
          endpoint: "http://{{ .Release.Name }}-victoria-logs-single-server:9428/insert/jsonline?_stream_fields=namespace&_msg_field=message&_time_field=timestamp"
          headers:
            Content-Type: "application/x-ndjson"
          layout:
            # Main event fields
            message: "{{ "{{ .Message }}" }}"
            timestamp: "{{ "{{ .GetTimestampISO8601 }}" }}"
            
            # Event classification
            event_type: "{{ "{{ .Type }}" }}"
            reason: "{{ "{{ .Reason }}" }}"
            
            # Kubernetes object info
            kind: "{{ "{{ .InvolvedObject.Kind }}" }}"
            name: "{{ "{{ .InvolvedObject.Name }}" }}"
            namespace: "{{ "{{ .Namespace }}" }}"
            
            # Source information
            component: "{{ "{{ .Source.Component }}" }}"
            host: "{{ "{{ .Source.Host }}" }}"
            
            # Event metadata
            count: "{{ "{{ .Count }}" }}"
            first_seen: "{{ "{{ .FirstTimestamp }}" }}"
            last_seen: "{{ "{{ .LastTimestamp }}" }}"
{{- end }}