{{- if .Values.eventExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "victoria-logs.eventExporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "victoria-logs.labels" . | nindent 4 }}
    app.kubernetes.io/component: event-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "victoria-logs.eventExporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "victoria-logs.eventExporter.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '2112'
        prometheus.io/path: '/metrics'
        checksum/config: {{ include (print $.Template.BasePath "/event-exporter-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "victoria-logs.eventExporter.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: event-exporter
          image: "{{ .Values.eventExporter.image.repository }}:{{ .Values.eventExporter.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            {{- toYaml .Values.eventExporter.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 2112
              protocol: TCP
      volumes:
        - name: config
          configMap:
            name: {{ include "victoria-logs.eventExporter.fullname" . }}-config
{{- end }}