apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: ClusterIP # Change to LoadBalancer or use Ingress if needed
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-kubernetes

